// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: proto/transfer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proto_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proto_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Account) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type TransferRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SenderAccount   *Account               `protobuf:"bytes,1,opt,name=senderAccount,proto3" json:"senderAccount,omitempty"`
	ReceiverAccount *Account               `protobuf:"bytes,2,opt,name=receiverAccount,proto3" json:"receiverAccount,omitempty"`
	TransferAmount  int64                  `protobuf:"varint,3,opt,name=transferAmount,proto3" json:"transferAmount,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Reason          string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_proto_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *TransferRequest) GetSenderAccount() *Account {
	if x != nil {
		return x.SenderAccount
	}
	return nil
}

func (x *TransferRequest) GetReceiverAccount() *Account {
	if x != nil {
		return x.ReceiverAccount
	}
	return nil
}

func (x *TransferRequest) GetTransferAmount() int64 {
	if x != nil {
		return x.TransferAmount
	}
	return 0
}

func (x *TransferRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransferRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TransferResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Reason          string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	ConvertedAmount int64                  `protobuf:"varint,3,opt,name=convertedAmount,proto3" json:"convertedAmount,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_proto_transfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_transfer_proto_rawDescGZIP(), []int{2}
}

func (x *TransferResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransferResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TransferResponse) GetConvertedAmount() int64 {
	if x != nil {
		return x.ConvertedAmount
	}
	return 0
}

var File_proto_transfer_proto protoreflect.FileDescriptor

const file_proto_transfer_proto_rawDesc = "" +
	"\n" +
	"\x14proto/transfer.proto\x12\btransfer\"K\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\"\xdf\x01\n" +
	"\x0fTransferRequest\x127\n" +
	"\rsenderAccount\x18\x01 \x01(\v2\x11.transfer.AccountR\rsenderAccount\x12;\n" +
	"\x0freceiverAccount\x18\x02 \x01(\v2\x11.transfer.AccountR\x0freceiverAccount\x12&\n" +
	"\x0etransferAmount\x18\x03 \x01(\x03R\x0etransferAmount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"l\n" +
	"\x10TransferResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12(\n" +
	"\x0fconvertedAmount\x18\x03 \x01(\x03R\x0fconvertedAmount2^\n" +
	"\x12TransactionService\x12H\n" +
	"\x0fValidateBalance\x12\x19.transfer.TransferRequest\x1a\x1a.transfer.TransferResponse2[\n" +
	"\x11ConversionService\x12F\n" +
	"\rConvertAmount\x12\x19.transfer.TransferRequest\x1a\x1a.transfer.TransferResponseB'Z%golang-simple_microservice-grpc/protob\x06proto3"

var (
	file_proto_transfer_proto_rawDescOnce sync.Once
	file_proto_transfer_proto_rawDescData []byte
)

func file_proto_transfer_proto_rawDescGZIP() []byte {
	file_proto_transfer_proto_rawDescOnce.Do(func() {
		file_proto_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_transfer_proto_rawDesc), len(file_proto_transfer_proto_rawDesc)))
	})
	return file_proto_transfer_proto_rawDescData
}

var file_proto_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_transfer_proto_goTypes = []any{
	(*Account)(nil),          // 0: transfer.Account
	(*TransferRequest)(nil),  // 1: transfer.TransferRequest
	(*TransferResponse)(nil), // 2: transfer.TransferResponse
}
var file_proto_transfer_proto_depIdxs = []int32{
	0, // 0: transfer.TransferRequest.senderAccount:type_name -> transfer.Account
	0, // 1: transfer.TransferRequest.receiverAccount:type_name -> transfer.Account
	1, // 2: transfer.TransactionService.ValidateBalance:input_type -> transfer.TransferRequest
	1, // 3: transfer.ConversionService.ConvertAmount:input_type -> transfer.TransferRequest
	2, // 4: transfer.TransactionService.ValidateBalance:output_type -> transfer.TransferResponse
	2, // 5: transfer.ConversionService.ConvertAmount:output_type -> transfer.TransferResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_transfer_proto_init() }
func file_proto_transfer_proto_init() {
	if File_proto_transfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_transfer_proto_rawDesc), len(file_proto_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_transfer_proto_goTypes,
		DependencyIndexes: file_proto_transfer_proto_depIdxs,
		MessageInfos:      file_proto_transfer_proto_msgTypes,
	}.Build()
	File_proto_transfer_proto = out.File
	file_proto_transfer_proto_goTypes = nil
	file_proto_transfer_proto_depIdxs = nil
}
